import { AppDataSource } from '../config/data-source';
import { User, UserRole } from '../entities/User';
import { Inventario, SucursalEnum, AreaEnum, ActivoEstado } from '../entities/Inventario';
// import { InventarioNuevo } from '../entities/InventarioNuevo';
import { AuthService } from '../services/AuthService';
import { Logger } from '../utils/logger';

/**
 * Script de seed para poblar la base de datos con datos de prueba
 *
 * Ejecutar con: pnpm seed
 */

async function seed() {
  try {
    // Inicializar conexión a BD
    await AppDataSource.initialize();
    Logger.info('✅ Conexión a base de datos establecida');

    const authService = new AuthService();
    const userRepository = AppDataSource.getRepository(User);
    const inventarioRepository = AppDataSource.getRepository(Inventario);
    // const inventarioNuevoRepository = AppDataSource.getRepository(InventarioNuevo);

    // ==================== USUARIOS ====================
    Logger.info('📦 Creando usuarios de prueba...');

    // Verificar si ya existen usuarios
    const existingUsers = await userRepository.count();
    if (existingUsers > 0) {
      Logger.warn(`Ya existen ${existingUsers} usuarios. Omitiendo creación de usuarios.`);
    } else {
      const users = [
        {
          dni: '12345678',
          nombre: 'Juan Pérez Administrador',
          direccion: 'Av. Principal 123, Lima',
          celular: '987654321',
          correo1: 'admin@activos.com',
          correo2: 'juan.perez@activos.com',
          rol: UserRole.ADMINISTRADOR,
          username: 'admin',
          password: '12345678', // Será hasheado
          activo: true,
          must_change_password: false,
        },
        {
          dni: '87654321',
          nombre: 'María García Coordinadora',
          direccion: 'Jr. Secundaria 456, Lima',
          celular: '912345678',
          correo1: 'coordinador@activos.com',
          correo2: 'maria.garcia@activos.com',
          rol: UserRole.COORDINADOR,
          username: 'coordinador',
          password: '87654321',
          activo: true,
          must_change_password: false,
        },
        {
          dni: '11223344',
          nombre: 'Carlos López Registrador',
          direccion: 'Calle Tercera 789, Lima',
          celular: '998877665',
          correo1: 'registrador@activos.com',
          correo2: 'carlos.lopez@activos.com',
          rol: UserRole.REGISTRADOR,
          username: 'registrador',
          password: '11223344',
          activo: true,
          must_change_password: false,
        },
        {
          dni: '99887766',
          nombre: 'Ana Torres Registradora',
          direccion: 'Av. Cuarta 321, Lima',
          celular: '955443322',
          correo1: 'registrador2@activos.com',
          correo2: 'ana.torres@activos.com',
          rol: UserRole.REGISTRADOR,
          username: 'registrador2',
          password: '99887766',
          activo: true,
          must_change_password: false,
        },
      ];

      for (const userData of users) {
        const passwordHash = await authService.hashPassword(userData.password);
        const user = userRepository.create({
          ...userData,
          password_hash: passwordHash,
        });
        await userRepository.save(user);
        Logger.info(`  ✓ Usuario creado: ${user.username} (${user.rol})`);
      }
    }

    // ==================== INVENTARIO HISTÓRICO ====================
    Logger.info('📦 Creando inventario histórico de prueba...');

    const existingInventario = await inventarioRepository.count();
    if (existingInventario > 0) {
      Logger.info(`Eliminando ${existingInventario} registros existentes en inventario...`);
      const allInventario = await inventarioRepository.find();
      await inventarioRepository.remove(allInventario);
    }

    {
      const inventarioData = [
        {
          cod_patrimonial: 'AF-2024-001',
          cod_etiqueta: 'ETQ-001',
          cod_af: 'AF001',
          descripcion: 'Laptop HP ProBook 450 G8',
          marca: 'HP',
          modelo: 'ProBook 450 G8',
          tipo_equipo: 'Laptop',
          serie: 'HPK8X123456',
          color: 'Gris',
          dimension: '35.6 x 23.4 x 1.9 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Oficina 201',
          fecha_adquisicion: new Date('2024-01-15'),
          monto_adquisicion: 3500.00,
          cod_responsable: 'R1-1',
          nombre_responsable: 'Pedro Martínez',
          observaciones1: 'Equipo asignado al área de operaciones',
          observaciones2: 'En buen estado de conservación',
        },
        {
          cod_patrimonial: 'AF-2024-002',
          cod_etiqueta: 'ETQ-002',
          cod_af: 'AF002',
          descripcion: 'Impresora Multifuncional Canon',
          marca: 'Canon',
          modelo: 'PIXMA G6020',
          tipo_equipo: 'Impresora',
          serie: 'CNG6020789',
          color: 'Negro',
          dimension: '44.5 x 36.8 x 16.8 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.LOGISTICA,
          ubicacion: 'Sala de impresión',
          fecha_adquisicion: new Date('2024-02-10'),
          monto_adquisicion: 1200.00,
          cod_responsable: 'R1-2',
          nombre_responsable: 'Laura Sánchez',
          observaciones1: 'Impresora compartida del área',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-003',
          cod_etiqueta: 'ETQ-003',
          cod_af: 'AF003',
          descripcion: 'Monitor Dell 24 pulgadas',
          marca: 'Dell',
          modelo: 'P2422H',
          tipo_equipo: 'Monitor',
          serie: 'DELL24P2422',
          color: 'Negro',
          dimension: '53.7 x 40.6 x 17.5 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.CAPANIQUE,
          cod_area: AreaEnum.CONTABILIDAD,
          ubicacion: 'Oficina 105',
          fecha_adquisicion: new Date('2024-03-05'),
          monto_adquisicion: 850.00,
          cod_responsable: 'R2-1',
          nombre_responsable: 'Roberto Flores',
          observaciones1: 'Monitor para estación de trabajo',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2023-100',
          cod_etiqueta: 'ETQ-100',
          cod_af: 'AF100',
          descripcion: 'Escritorio de Oficina',
          marca: 'Oficentro',
          modelo: 'ESC-150',
          tipo_equipo: 'Mobiliario',
          serie: 'ESC150-2023',
          color: 'Marrón',
          dimension: '150 x 75 x 75 cm',
          estado: ActivoEstado.REGULAR_BUENO,
          cod_sucursal: SucursalEnum.POSTGRADO,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Aula 302',
          fecha_adquisicion: new Date('2023-08-20'),
          monto_adquisicion: 450.00,
          cod_responsable: 'R3-1',
          nombre_responsable: 'Carmen Rojas',
          observaciones1: 'Mobiliario de aula',
          observaciones2: 'Requiere mantenimiento menor',
        },
        {
          cod_patrimonial: 'AF-2023-101',
          cod_etiqueta: 'ETQ-101',
          cod_af: 'AF101',
          descripcion: 'Proyector Epson PowerLite',
          marca: 'Epson',
          modelo: 'PowerLite E20',
          tipo_equipo: 'Proyector',
          serie: 'EPSON-E20-456',
          color: 'Blanco',
          dimension: '30 x 23 x 9 cm',
          estado: ActivoEstado.REGULAR_BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Sala de conferencias',
          fecha_adquisicion: new Date('2023-09-15'),
          monto_adquisicion: 2100.00,
          cod_responsable: 'R1-3',
          nombre_responsable: 'Miguel Vega',
          observaciones1: 'Proyector de sala de conferencias',
          observaciones2: 'Lámpara con 500 horas de uso',
        },
        {
          cod_patrimonial: 'AF-2024-004',
          cod_etiqueta: 'ETQ-004',
          cod_af: 'AF004',
          descripcion: 'Silla ergonómica ejecutiva',
          marca: 'Herman Miller',
          modelo: 'Aeron Size B',
          tipo_equipo: 'Mobiliario',
          serie: 'HM-AERON-B-2024',
          color: 'Negro',
          dimension: '66 x 66 x 100 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Oficina Gerencia',
          fecha_adquisicion: new Date('2024-01-20'),
          monto_adquisicion: 1800.00,
          cod_responsable: 'R1-1',
          nombre_responsable: 'Pedro Martínez',
          observaciones1: 'Silla ergonómica para gerencia',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-005',
          cod_etiqueta: 'ETQ-005',
          cod_af: 'AF005',
          descripcion: 'Teclado mecánico Logitech',
          marca: 'Logitech',
          modelo: 'MX Keys',
          tipo_equipo: 'Periférico',
          serie: 'LG-MXK-789',
          color: 'Gris oscuro',
          dimension: '43 x 13 x 2.6 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.CAPANIQUE,
          cod_area: AreaEnum.LOGISTICA,
          ubicacion: 'Almacén principal',
          fecha_adquisicion: new Date('2024-02-15'),
          monto_adquisicion: 250.00,
          cod_responsable: 'R2-2',
          nombre_responsable: 'Ana Silva',
          observaciones1: 'Teclado inalámbrico',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-006',
          cod_etiqueta: 'ETQ-006',
          cod_af: 'AF006',
          descripcion: 'Mouse inalámbrico Logitech',
          marca: 'Logitech',
          modelo: 'MX Master 3',
          tipo_equipo: 'Periférico',
          serie: 'LG-MXM3-456',
          color: 'Negro',
          dimension: '12.5 x 8.4 x 5.1 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.CAPANIQUE,
          cod_area: AreaEnum.CONTABILIDAD,
          ubicacion: 'Oficina 105',
          fecha_adquisicion: new Date('2024-03-01'),
          monto_adquisicion: 150.00,
          cod_responsable: 'R2-1',
          nombre_responsable: 'Roberto Flores',
          observaciones1: 'Mouse ergonómico',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-007',
          cod_etiqueta: 'ETQ-007',
          cod_af: 'AF007',
          descripcion: 'Aire acondicionado LG 18000 BTU',
          marca: 'LG',
          modelo: 'Dual Inverter S4-W18KLAPB',
          tipo_equipo: 'Climatización',
          serie: 'LG-AC-18K-789',
          color: 'Blanco',
          dimension: '99 x 34.5 x 23 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Sala de servidores',
          fecha_adquisicion: new Date('2024-03-10'),
          monto_adquisicion: 2500.00,
          cod_responsable: 'R1-1',
          nombre_responsable: 'Pedro Martínez',
          observaciones1: 'Aire acondicionado para sala de servidores',
          observaciones2: 'Con control remoto',
        },
        {
          cod_patrimonial: 'AF-2024-008',
          cod_etiqueta: 'ETQ-008',
          cod_af: 'AF008',
          descripcion: 'Router Cisco Business',
          marca: 'Cisco',
          modelo: 'RV340',
          tipo_equipo: 'Red',
          serie: 'CISCO-RV340-123',
          color: 'Negro',
          dimension: '22 x 18 x 4.4 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Cuarto de telecomunicaciones',
          fecha_adquisicion: new Date('2024-04-05'),
          monto_adquisicion: 850.00,
          cod_responsable: 'R1-1',
          nombre_responsable: 'Pedro Martínez',
          observaciones1: 'Router principal de red',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-009',
          cod_etiqueta: 'ETQ-009',
          cod_af: 'AF009',
          descripcion: 'Switch TP-Link 24 puertos',
          marca: 'TP-Link',
          modelo: 'TL-SG1024D',
          tipo_equipo: 'Red',
          serie: 'TPL-SG24-456',
          color: 'Negro',
          dimension: '44 x 18 x 4.4 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Cuarto de telecomunicaciones',
          fecha_adquisicion: new Date('2024-04-05'),
          monto_adquisicion: 320.00,
          cod_responsable: 'R1-1',
          nombre_responsable: 'Pedro Martínez',
          observaciones1: 'Switch de red 24 puertos Gigabit',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-010',
          cod_etiqueta: 'ETQ-010',
          cod_af: 'AF010',
          descripcion: 'UPS APC Smart 1500VA',
          marca: 'APC',
          modelo: 'SMC1500I',
          tipo_equipo: 'Energía',
          serie: 'APC-SMC1500-789',
          color: 'Negro',
          dimension: '14.5 x 36 x 21.5 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Sala de servidores',
          fecha_adquisicion: new Date('2024-04-10'),
          monto_adquisicion: 950.00,
          cod_responsable: 'R1-1',
          nombre_responsable: 'Pedro Martínez',
          observaciones1: 'UPS para servidores',
          observaciones2: 'Batería nueva',
        },
        {
          cod_patrimonial: 'AF-2024-011',
          cod_etiqueta: 'ETQ-011',
          cod_af: 'AF011',
          descripcion: 'Teléfono IP Cisco',
          marca: 'Cisco',
          modelo: '7841',
          tipo_equipo: 'Telefonía',
          serie: 'CISCO-7841-123',
          color: 'Gris',
          dimension: '22.9 x 24.6 x 5.8 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.POSTGRADO,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Recepción',
          fecha_adquisicion: new Date('2024-04-15'),
          monto_adquisicion: 320.00,
          cod_responsable: 'R3-1',
          nombre_responsable: 'Carmen Rojas',
          observaciones1: 'Teléfono IP recepción',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-012',
          cod_etiqueta: 'ETQ-012',
          cod_af: 'AF012',
          descripcion: 'Scanner Epson WorkForce',
          marca: 'Epson',
          modelo: 'ES-500W',
          tipo_equipo: 'Escaneo',
          serie: 'EPSON-ES500-456',
          color: 'Blanco',
          dimension: '28.7 x 8.8 x 6.7 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.CAPANIQUE,
          cod_area: AreaEnum.LOGISTICA,
          ubicacion: 'Almacén documentos',
          fecha_adquisicion: new Date('2024-04-20'),
          monto_adquisicion: 680.00,
          cod_responsable: 'R2-2',
          nombre_responsable: 'Ana Silva',
          observaciones1: 'Scanner portátil WiFi',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2023-102',
          cod_etiqueta: 'ETQ-102',
          cod_af: 'AF102',
          descripcion: 'Archivador metálico 4 gavetas',
          marca: 'Steelcase',
          modelo: 'FC-4G',
          tipo_equipo: 'Mobiliario',
          serie: 'STEEL-FC4-789',
          color: 'Gris',
          dimension: '46 x 62 x 132 cm',
          estado: ActivoEstado.REGULAR_BUENO,
          cod_sucursal: SucursalEnum.CAPANIQUE,
          cod_area: AreaEnum.CONTABILIDAD,
          ubicacion: 'Oficina contabilidad',
          fecha_adquisicion: new Date('2023-10-01'),
          monto_adquisicion: 550.00,
          cod_responsable: 'R2-1',
          nombre_responsable: 'Roberto Flores',
          observaciones1: 'Archivador documentos contables',
          observaciones2: 'Pequeños rayones en exterior',
        },
        {
          cod_patrimonial: 'AF-2024-013',
          cod_etiqueta: 'ETQ-013',
          cod_af: 'AF013',
          descripcion: 'Webcam Logitech HD Pro',
          marca: 'Logitech',
          modelo: 'C920',
          tipo_equipo: 'Periférico',
          serie: 'LG-C920-123',
          color: 'Negro',
          dimension: '9.4 x 4.3 x 7.1 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Sala conferencias',
          fecha_adquisicion: new Date('2024-05-01'),
          monto_adquisicion: 180.00,
          cod_responsable: 'R1-3',
          nombre_responsable: 'Miguel Vega',
          observaciones1: 'Cámara para videoconferencias',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-014',
          cod_etiqueta: 'ETQ-014',
          cod_af: 'AF014',
          descripcion: 'Microfono de conferencia Jabra',
          marca: 'Jabra',
          modelo: 'Speak 750',
          tipo_equipo: 'Audio',
          serie: 'JABRA-SP750-456',
          color: 'Negro',
          dimension: '12 x 12 x 3.5 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Sala conferencias',
          fecha_adquisicion: new Date('2024-05-01'),
          monto_adquisicion: 420.00,
          cod_responsable: 'R1-3',
          nombre_responsable: 'Miguel Vega',
          observaciones1: 'Micrófono speakerphone USB',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-015',
          cod_etiqueta: 'ETQ-015',
          cod_af: 'AF015',
          descripcion: 'Disco duro externo Seagate 2TB',
          marca: 'Seagate',
          modelo: 'Backup Plus',
          tipo_equipo: 'Almacenamiento',
          serie: 'SEAGATE-BP2TB-789',
          color: 'Negro',
          dimension: '11.7 x 8 x 2.1 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.CAPANIQUE,
          cod_area: AreaEnum.CONTABILIDAD,
          ubicacion: 'Oficina contabilidad',
          fecha_adquisicion: new Date('2024-05-10'),
          monto_adquisicion: 120.00,
          cod_responsable: 'R2-1',
          nombre_responsable: 'Roberto Flores',
          observaciones1: 'Disco para respaldos contables',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-016',
          cod_etiqueta: 'ETQ-016',
          cod_af: 'AF016',
          descripcion: 'Pizarra acrílica 120x90cm',
          marca: 'Quartet',
          modelo: 'Prestige 2',
          tipo_equipo: 'Mobiliario',
          serie: 'QUARTET-P2-123',
          color: 'Blanco',
          dimension: '120 x 90 x 2 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.POSTGRADO,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Aula 301',
          fecha_adquisicion: new Date('2024-05-15'),
          monto_adquisicion: 280.00,
          cod_responsable: 'R3-1',
          nombre_responsable: 'Carmen Rojas',
          observaciones1: 'Pizarra para aula',
          observaciones2: 'Incluye marcadores y borrador',
        },
        {
          cod_patrimonial: 'AF-2024-017',
          cod_etiqueta: 'ETQ-017',
          cod_af: 'AF017',
          descripcion: 'Estabilizador de voltaje CDP',
          marca: 'CDP',
          modelo: 'R-AVR 1208i',
          tipo_equipo: 'Energía',
          serie: 'CDP-AVR1208-456',
          color: 'Negro',
          dimension: '35 x 18 x 12 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.LOGISTICA,
          ubicacion: 'Área de impresión',
          fecha_adquisicion: new Date('2024-05-20'),
          monto_adquisicion: 180.00,
          cod_responsable: 'R1-2',
          nombre_responsable: 'Laura Sánchez',
          observaciones1: 'Estabilizador para equipos de impresión',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-018',
          cod_etiqueta: 'ETQ-018',
          cod_af: 'AF018',
          descripcion: 'Laptop Dell Latitude 5420',
          marca: 'Dell',
          modelo: 'Latitude 5420',
          tipo_equipo: 'Laptop',
          serie: 'DELL-LAT5420-789',
          color: 'Negro',
          dimension: '32.1 x 21.2 x 2 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.CAPANIQUE,
          cod_area: AreaEnum.LOGISTICA,
          ubicacion: 'Oficina logística',
          fecha_adquisicion: new Date('2024-05-25'),
          monto_adquisicion: 3200.00,
          cod_responsable: 'R2-2',
          nombre_responsable: 'Ana Silva',
          observaciones1: 'Laptop para coordinador logística',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-019',
          cod_etiqueta: 'ETQ-019',
          cod_af: 'AF019',
          descripcion: 'Calculadora científica Casio',
          marca: 'Casio',
          modelo: 'FX-991EX',
          tipo_equipo: 'Útiles de oficina',
          serie: 'CASIO-FX991-123',
          color: 'Negro',
          dimension: '16.6 x 7.7 x 1.1 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.CAPANIQUE,
          cod_area: AreaEnum.CONTABILIDAD,
          ubicacion: 'Oficina contabilidad',
          fecha_adquisicion: new Date('2024-06-01'),
          monto_adquisicion: 85.00,
          cod_responsable: 'R2-1',
          nombre_responsable: 'Roberto Flores',
          observaciones1: 'Calculadora científica',
          observaciones2: undefined,
        },
        {
          cod_patrimonial: 'AF-2024-020',
          cod_etiqueta: 'ETQ-020',
          cod_af: 'AF020',
          descripcion: 'Mesa de reuniones ejecutiva',
          marca: 'Steelcase',
          modelo: 'Conference 200x100',
          tipo_equipo: 'Mobiliario',
          serie: 'STEEL-CONF200-456',
          color: 'Madera oscura',
          dimension: '200 x 100 x 75 cm',
          estado: ActivoEstado.BUENO,
          cod_sucursal: SucursalEnum.SAN_MARTIN,
          cod_area: AreaEnum.OPERACIONES,
          ubicacion: 'Sala de reuniones',
          fecha_adquisicion: new Date('2024-06-05'),
          monto_adquisicion: 2800.00,
          cod_responsable: 'R1-1',
          nombre_responsable: 'Pedro Martínez',
          observaciones1: 'Mesa de reuniones para 8 personas',
          observaciones2: 'Incluye sistema de cableado integrado',
        },
      ];

      for (const data of inventarioData) {
        const inventario = inventarioRepository.create(data);
        await inventarioRepository.save(inventario);
        Logger.info(`  ✓ Inventario creado: ${inventario.cod_patrimonial} - ${inventario.descripcion}`);
      }
    }

    Logger.info('\n✅ Seed completado exitosamente');
    Logger.info('\n📋 Credenciales de acceso:');
    Logger.info('  👤 Administrador:');
    Logger.info('     Username: admin');
    Logger.info('     Password: 12345678\n');
    Logger.info('  👤 Coordinador:');
    Logger.info('     Username: coordinador');
    Logger.info('     Password: 87654321\n');
    Logger.info('  👤 Registrador:');
    Logger.info('     Username: registrador');
    Logger.info('     Password: 11223344\n');
    Logger.info('  👤 Registrador 2:');
    Logger.info('     Username: registrador2');
    Logger.info('     Password: 99887766\n');

    await AppDataSource.destroy();
    process.exit(0);
  } catch (error) {
    Logger.error('❌ Error en seed', {
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
    });
    process.exit(1);
  }
}

// Ejecutar seed
seed();
